//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostscript.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ghostscript.Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_add {
            get {
                object obj = ResourceManager.GetObject("_16x16_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_apply_preset {
            get {
                object obj = ResourceManager.GetObject("_16x16_apply_preset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_clear {
            get {
                object obj = ResourceManager.GetObject("_16x16_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_delete {
            get {
                object obj = ResourceManager.GetObject("_16x16_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_directory {
            get {
                object obj = ResourceManager.GetObject("_16x16_directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_preset_list {
            get {
                object obj = ResourceManager.GetObject("_16x16_preset_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_preset_save {
            get {
                object obj = ResourceManager.GetObject("_16x16_preset_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16x16_preset_set {
            get {
                object obj = ResourceManager.GetObject("_16x16_preset_set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;About Author&lt;/title&gt;
        ///        &lt;style&gt;
        ///            a:link {color:#0000EE;}
        ///            a:visited {color:#0000EE;}
        ///            a:hover {color:#0000EE;}
        ///            a:active {color:#0000EE;}
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body style=&quot;background-color: #bgcolor; margin: 0px; padding-top: 4px; padding-bottom: 4px; padding-left: 10px; font-family: Verdana; font-size: 12px; overflow: hidden;&quot;&gt;
        ///        &lt;div style=&quot;margin-bottom: 6px;&quot;&gt;
        ///            &lt;span&gt;Copyright (c) 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_main {
            get {
                return ResourceManager.GetString("about_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Translations&lt;/title&gt;
        ///        &lt;style&gt;
        ///            a:link {color:#0000EE;}
        ///            a:visited {color:#0000EE;}
        ///            a:hover {color:#0000EE;}
        ///            a:active {color:#0000EE;}
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body style=&quot;background-color: #bgcolor; margin: 0px; padding-top: 4px; padding-bottom: 4px; padding-left: 10px; font-family: Verdana; font-size: 12px; overflow: hidden;&quot;&gt;
        ///        #languages
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string about_translations {
            get {
                return ResourceManager.GetString("about_translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Components Used In Ghostscript.Studio&lt;/title&gt;
        ///        &lt;style&gt;
        ///            a:link {color:#0000EE;}
        ///            a:visited {color:#0000EE;}
        ///            a:hover {color:#0000EE;}
        ///            a:active {color:#0000EE;}
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body style=&quot;background-color: #bgcolor; margin: 0px; padding-top: 4px; padding-bottom: 4px; padding-left: 10px; font-family: Verdana; font-size: 12px; overflow: hidden;&quot;&gt;
        ///        &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspaci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_used_components {
            get {
                return ResourceManager.GetString("about_used_components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_copy {
            get {
                object obj = ResourceManager.GetObject("edit_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_cut {
            get {
                object obj = ResourceManager.GetObject("edit_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_paste {
            get {
                object obj = ResourceManager.GetObject("edit_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_redo {
            get {
                object obj = ResourceManager.GetObject("edit_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_undo {
            get {
                object obj = ResourceManager.GetObject("edit_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_new {
            get {
                object obj = ResourceManager.GetObject("file_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_open {
            get {
                object obj = ResourceManager.GetObject("file_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_save {
            get {
                object obj = ResourceManager.GetObject("file_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_save_all {
            get {
                object obj = ResourceManager.GetObject("file_save_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ghostscript_help_en_US {
            get {
                object obj = ResourceManager.GetObject("ghostscript_help_en_US", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ghostscript_Studio {
            get {
                object obj = ResourceManager.GetObject("Ghostscript_Studio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;switches&gt;
        ///	&lt;switch type=&quot;OnOff&quot; category=&quot;INTERACTION&quot;&gt;
        ///		&lt;name&gt;-dSAFER&lt;/name&gt;
        ///	&lt;/switch&gt;
        ///
        ///	&lt;switch type=&quot;OnOff&quot; category=&quot;INTERACTION&quot;&gt;
        ///		&lt;name&gt;-dNOPAUSE&lt;/name&gt;
        ///	&lt;/switch&gt;
        ///
        ///	&lt;switch type=&quot;OnOff&quot; category=&quot;INTERACTION&quot;&gt;
        ///		&lt;name&gt;-dNOPROMPT&lt;/name&gt;
        ///	&lt;/switch&gt;
        ///
        ///	&lt;switch type=&quot;OnOff&quot; category=&quot;OTHER&quot;&gt;
        ///		&lt;name&gt;-dBATCH&lt;/name&gt;
        ///	&lt;/switch&gt;
        ///
        ///	&lt;switch type=&quot;Folder(;)&quot; category=&quot;FONT_RELATED&quot;&gt;
        ///		&lt;name&gt;-sFONTPATH&lt;/name&gt;
        ///	&lt;/switch&gt;
        ///
        ///	&lt;switch type=&quot;Integer(1-N) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gs_switches {
            get {
                return ResourceManager.GetString("gs_switches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GSN_GSS_icon {
            get {
                object obj = ResourceManager.GetObject("GSN_GSS_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon gss {
            get {
                object obj = ResourceManager.GetObject("gss", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] language_en_US {
            get {
                object obj = ResourceManager.GetObject("language_en_US", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run_start {
            get {
                object obj = ResourceManager.GetObject("run_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run_stop {
            get {
                object obj = ResourceManager.GetObject("run_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_first {
            get {
                object obj = ResourceManager.GetObject("view_first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_last {
            get {
                object obj = ResourceManager.GetObject("view_last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_next {
            get {
                object obj = ResourceManager.GetObject("view_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_previous {
            get {
                object obj = ResourceManager.GetObject("view_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_zoom_in {
            get {
                object obj = ResourceManager.GetObject("view_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_zoom_out {
            get {
                object obj = ResourceManager.GetObject("view_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
